---
title: "hw_3_code"
author: "Danielle Sclafani"
date: "5/5/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(here)
library(janitor)
```

```{r}
# load data
data <- read_csv(here("data", "HW3_data.csv")) %>% 
  clean_names()
 
plot_data <- data %>% 
  gather(income_group, gallons_demanded, q_low_gallons:q_high_gallons) #gathering data by new column we named income group, and put the inflow from q_low_gallons and q_high_gallons into a new column called gallons_demanded

#plotting the data

scatter_demand <- ggplot(data = plot_data, aes(y = price_dollars, x = gallons_demanded)) + geom_point()+
  facet_wrap(~income_group)+
  geom_smooth(method = lm) #adding a linear trend line the way i know how to


scatter_demand

```

### Linear Model    
```{r}

model_low <- lm(price_dollars ~ q_low_gallons, data = data) #created the linear models based on the data we have
model_high <- lm(price_dollars ~ q_high_gallons, data = data)

# prediction functions- creating the function

predict_curve <- function(gallons, model){
  bO <-model$coefficients[1]
  b1 <- model$coefficients[2]
  
  predicted_curve <- bO +b1*gallons
  
  return(as.numeric(predicted_curve))
}

# creating a vector to put into the linear model - from 0 to 500000

gallons_q <- seq(0, 500000, length.out = 500000)


# predict linear Demand curves of gasoline for each income group and store as data frames. data frames names are high and low

high <- bind_cols(gallons_q = gallons_q,
                  linear_price = predict_curve(gallons_q, model_high), income_group = "high") #use the function you made above, the vector from 1 to and the model you made from the available data to predict the linear line (linear because you ran a linear model above)

low <- bind_cols(gallons_q = gallons_q,
                  linear_price = predict_curve(gallons_q, model_low), income_group = "low")

predict_mb_gas <- bind_rows(high, low) #combines the two predicted curves into one data frame

```


```{r}
a <- model_low$coefficients[[1]] #intercept
b <- model_low$coefficients[[2]] #slope
a1 <- model_high$coefficients[[1]] #intercept
b2 <-model_high$coefficients[[2]] #slope
```


```{r}
## Plot predicted Demand curves

ggplot(data = predict_mb_gas, aes(x = gallons_q, y = linear_price)) + geom_point(aes(col = "income_group")) +
  geom_line(data = supply_data, aes(x=gallons_q, y = price))+
geom_line(data = agg_data, aes(x=gallons_q, y = price)) 
```



```{r}
# finding the aggregate demand curve

demand_agg <- function(p, model, model2){
  q <- (p-model$coefficient[[1]]/model$coefficient[[2]]) + (p-model2$coefficient[[1]]/model2$coefficient[[2]])
  return(q)
}

demand_inverse_agg<- function(q, model, model2){
  p <- model$coefficients[[1]] + model$coefficients[[2]]*q + model2$coefficients[[1]] + model2$coefficients[[2]]*q
  return(p) # dont think this one is accurate
}

demand_inverse_agg(0,model_low, model_high) # y-intercept? - dont think this is accurate

demand_agg(0,model_low, model_high) # x-intercept

aggregate <- bind_cols(gallons_q = gallons_q,
                  linear_price = demand_agg(gallons_q, model_high, model_low))

ggplot(data = aggregate, aes(x = gallons_q, y = linear_price)) + geom_point()

```


#calculating consumer surplus
```{r}
#supply curve : P = 3Q

supply <- function(x){
  p <- 0.00000499*x
  return(p)
}

supply_data <- bind_cols(gallons_q = gallons_q,
                  price = supply(gallons_q))

#manually putting in the aggregate curve
man_agg <- function(x){
  p <- -0.000019*x + 14.6
  return(p)
}

agg_data <- bind_cols(gallons_q = gallons_q,
                  price = man_agg(gallons_q))
```


```{r}
#finding consumer surplus - input q
# found where each curve intersects the supply curve

#not with the aggregate

inverse_demand <- function(q, model){
  p <- model$coefficients[[1]] + model$coefficients[[2]]*q 
  return(p)
}

cs_q <- function(q, model){
  p <- inverse_demand(q, model)
  cs<- 0.5*(model$coefficient[[1]] -p)*q
  return(cs)
}

high_cs <- cs_q(489281, model_high)

high_cs #3,268,863

low_cs <- cs_q(164349, model_low)
low_cs #892,894.2

total_surplus <- high_cs + low_cs

total_surplus #4,161,757
```



